### ISSUE TITLE
Packets loss

### ISSUE THREAD

**Issue by ct1esj** [nakhonthai/ESP32APRS_T-TWR#16]
Two suggestions if I may:
First: SQL opens slightly late, so some packets are lost and are not decoded. If SQL is set to 0, then yes, it catches everything.

Second: It would be nice if the volume could be set to 0.

Thank you for all the excellent work, otherwise everything is perfect.

**Comment by lyusupov** [comment]
> Second: It would be nice if the volume could be set to 0.

https://file.fomille.site/1260815565112336386/1693512722272129026.pdf

<img width="616" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/0c8b95fd-9100-4edf-b17e-623d15c6dc55">

**Comment by ct1esj** [comment]
OK, thanks for the info about volume.

And SQL?
