### ISSUE TITLE
0.3b: Username/password for Webinterface

### ISSUE THREAD

**Issue by grisuat** [nakhonthai/ESP32APRS_T-TWR#18]
Has anyone other experienced problems when trying to log into the webinterface with firmware 0.3b? 

It works perfectly with 0.3 and I can change settings. When I upgrade via OTA to 0.3b no login with admin/admin is possible. When I downgrade to 0.3 again, it works again.

**Comment by lyusupov** [comment]
I had the same issue...

Use OLED UI to reset device into factory default settings.
WebUi admin password works nicely to me after that action.

**Comment by grisuat** [comment]
Thanks, that did the job.
