### ISSUE TITLE
No decode Package

### ISSUE THREAD

**Issue by ct1esj** [nakhonthai/ESP32APRS_T-TWR#20]
Do not decode any aprs package with SQL closed.
Am I configuring it wrong?
I have V0.3a

**Comment by nakhonthai** [comment]
SQL=0 is mean noise on audio.
You can test by open HPF or BPF mode.

**Comment by ct1esj** [comment]
I have been trying to play with HPF and BPF, some results were achieved this way with BPF open, it already decodes some packets, not all or a good part of them.

**Comment by ct1esj** [comment]
Anyway, it seems to me that SQL opens too late, SQL opens but no longer receives anything because it is the final part of the package and closes soon. I made a comparison with a Yaesu FT-5 and it turns out that on the radio the SQL opens immediately and the Lilygo remains silent.

**Comment by ericmoritz** [comment]
I think I figured this out with my device at least. I could not for the life of me figure out how to get packets to decode. I'd hear them out the speaker, but very few would show up.

I set the squelch to 0, that seemed to help a little, but it still wasn't the volume of APRS messages I'd see using direwolf connected to my base station.

I accidentally broke the speaker's JST connector, so on a whim, I said, hey, what if I set the volume to max?

Sure enough, as soon as I set the volume to 8, packets started flooding in. I'd see Direwolf decode a message, and then I'd see it show up in the web interface.

I assumed the volume was for the speaker, but it appears that it controls the audio volume to the decoder as well.

Details:

```
Hardware Version: 	LILYGO T-TWR Plus
Firmware Version: 	V0.4
RF Analog Module: 	MODEL: SA868_VHF
ESP32 Model: 	ESP32-S3
Chip ID: 	78EB470CDADC
Revision: 	0
Flash: 	16777 KByte
PSRAM: 	8385 KByte
```

**Comment by ct1esj** [comment]
> I think I figured this out with my device at least. I could not for the life of me figure out how to get packets to decode. I'd hear them out the speaker, but very few would show up.
> 
> I set the squelch to 0, that seemed to help a little, but it still wasn't the volume of APRS messages I'd see using direwolf connected to my base station.
> 
> I accidentally broke the speaker's JST connector, so on a whim, I said, hey, what if I set the volume to max?
> 
> Sure enough, as soon as I set the volume to 8, packets started flooding in. I'd see Direwolf decode a message, and then I'd see it show up in the web interface.
> 
> I assumed the volume was for the speaker, but it appears that it controls the audio volume to the decoder as well.
> 
> Details:
> 
> ```
> Hardware Version: 	LILYGO T-TWR Plus
> Firmware Version: 	V0.4
> RF Analog Module: 	MODEL: SA868_VHF
> ESP32 Model: 	ESP32-S3
> Chip ID: 	78EB470CDADC
> Revision: 	0
> Flash: 	16777 KByte
> PSRAM: 	8385 KByte
> ```

Well, in my case I set the volume to maximum, 8. The squelch is at 1 so it receives and decodes everything. I also came to the conclusion that the volume level affects the decoding of packets. But as the volume is at maximum, I disconnected the speaker connector.
