### ISSUE TITLE
WIFI AP shows intermittently, unable to connect from multiple devices

### ISSUE THREAD

**Issue by shiftyp** [nakhonthai/ESP32APRS_T-TWR#22]
With the default settings, I've tried connecting to the WiFi AP to access the config page, and the WiFi AP will appear, then disappear, and when available my devices (Windows 10 laptop and Android Phone Pixel 7) are unable to complete a connection. I've tried changing the WiFi power on the AP side, as well as turning off and on services to no effect. Any tips on how I can further debug?

**Comment by nakhonthai** [comment]
To use wifi client mode.
by share wifi from smartphone or router.
SSID: APRSTH
Pass: aprsthnetwork

**Comment by lyusupov** [comment]
https://github.com/nakhonthai/ESP32APRS_T-TWR/discussions/10

**Comment by shiftyp** [comment]
Thanks, I see this is a duplicate. It might be good to add a link to #10 in the documentation to highlight this issue. I was also slightly confused by the term "WiFi Station" which I would probably call "WiFi Client". Closing
