### ISSUE TITLE
VHF RX but no RF transmission on TX

### ISSUE THREAD

**Issue by shiftyp** [nakhonthai/ESP32APRS_T-TWR#24]
I've tried setting up both the VHF and UHF models, and I can RX at least on VHF but can't transmit in Tracker mode. I've verified this with both an HT and an SDR tuned to the TX frequency. Here is my setup.

![Screenshot_20240203-090600.png](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/131928/1e3b09d3-1bc9-4659-b0bc-7b3b717a436b)

![Screenshot_20240203-090534.png](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/131928/f0b6bc26-b400-4f00-ab5b-b4250ccfe5f4)

![Screenshot_20240203-090618.png](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/131928/206f9fa2-68cc-42ff-bf8a-612650b73282)

**Comment by shiftyp** [comment]
Closing, after checking I realized I have the edition with the SA868S transceiver

**Comment by nakhonthai** [comment]
Manual TX by 
- Push PTT for TX voice +package tracking
- Push B0 for TX package tracking
