### ISSUE TITLE
Audio out - Disable ?

### ISSUE THREAD

**Issue by banshee1971** [nakhonthai/ESP32APRS_T-TWR#35]
Been able to disable the speaker, would be nice.

**Comment by lyusupov** [comment]
Muting SA868 volume level down to 0 will cost you to no receive APRS at all.

Just unplug speaker connector (black and red wires) if it hurts.

**Comment by VK1MIC** [comment]
I’ve not been able to get the open to receive anything anyway

Wade Smith
m: +61403956763
w: wadeabout.com  e: ***@***.***

**Comment by lyusupov** [comment]
> able to get the open to receive

I can see from the ESP32APRS_T-TWR source code that implementation of APRS receive function with `Open Edition` firmware is incomplete. IMHO, it was a premature decision to make it a part of the recent release.

APRS receive with NiceRF firmware works more or less fine to me.

**Comment by banshee1971** [comment]
> Muting SA868 volume level down to 0 will cost you to no receive APRS at all.
> 
> Just unplug the speaker connector (black and red wires) if it hurts.

I just did that :)

**Comment by lyusupov** [comment]
@banshee1971 

<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">
