### ISSUE TITLE
Turn off speaker 

### ISSUE THREAD

**Issue by Russell-KV4S** [nakhonthai/ESP32APRS_T-TWR#36]
How do I turn off or remove the speaker?

Is it the round thing between the boot and reset button?

**Comment by VK1MIC** [comment]
Pull the plug on the end of the curly cable labeled speaker

Wade Smith
m: +61403956763
w: wadeabout.com  e: ***@***.***

**Comment by Russell-KV4S** [comment]
SPK?

Like I did in the picture?:

**Comment by Russell-KV4S** [comment]
Picture didn't come through.

That was it. SPK.
I didn't see that at first, the wires were in the way.

![PXL_20240416_011939249](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/13912121/12a02b78-f8e5-4325-bc5f-a5224d32d77b)

**Comment by Russell-KV4S** [comment]
Unplug SPK wire.
