### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by lyusupov** [nakhonthai/ESP32APRS_T-TWR#4]
Version: 0.2**b**

<img width="744" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/999e76d6-fb0e-4841-8a8a-ae2666900db8">

<br>
<br>

There are numerous appearances of the typo:

<br>
<br>

<img width="828" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/e41a6b76-5379-47b7-9d18-e6516faeccb0">

<br>
<br>

### Suggested replacement

Infomations -> **Information**

**Comment by nakhonthai** [comment]
Thank you,
Fix in the V0.2c

**Comment by lyusupov** [comment]
One more 'cosmetic' issue -

Don't you think that there are too many '**ESP32**' labels here:

<img width="300" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/321aa0cb-c581-4670-9b27-66c474b30487">

Would it make sense to keep the first one only ?

**Comment by nakhonthai** [comment]
OK,Fix in the V0.2e
