### ISSUE TITLE
[Feature] request for an option to add time stamp into iGate beacon

### ISSUE THREAD

**Issue by lyusupov** [nakhonthai/ESP32APRS_T-TWR#5]
<img width="497" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/9c754564-0697-475b-87ff-ca515114db62">

Certain APRS-IS servers _(such as aprs.glidernet.org)_ can reject iGate TCP beacons that do not have a time stamp. This makes the ESP32APRS iGate not shown on the GliderNet APRS map websites...

Even though the time stamp is not a mandatory field, is it possible to supply the time stamp as well ?

The stamp uses UTC time _(GMT+0h time zone)_.

**Comment by nakhonthai** [comment]
Update in the version 0.3
