### ISSUE TITLE
Support OpenRTX sa8x8 FW 

### ISSUE THREAD

**Issue by assada** [nakhonthai/ESP32APRS_T-TWR#8]
For OpenEdition versions of T-TWR, there is a project from the OpenRTX team https://github.com/OpenRTX/sa8x8-fw

It would be nice to add support for this firmware in the project. Currently, it lacks AT commands that are in the official(NiceRF) one. But in case you have OpenEdition, then the ESP32APRS_T-TWR project is not suitable for you. However, if you add communication through i2c directly, this can be fixed. In my opinion, this is an exhaustive example of full support for 868 through i2c directly: https://github.com/OpenRTX/sa8x8-fw/blob/main/api/python/sa8x8.py

**Comment by nakhonthai** [comment]
Hardware does not support updates direct from ESP32,Not wire connected i2c or spi gpio for program.
You need programs and other hardware to program it at CN4 connector.
![image](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/16043758/daeec62c-9c7f-4d00-92da-d7a5c595288e)
![image](https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/16043758/94418c73-bb9b-4881-af03-33f748b07027)

Firmware from OpenRTX ,it AT-Command not match with original.
Therefore it is difficult for users. To program the RF module to match the original.

**Comment by assada** [comment]
I am not talking about replacing the firmware of the module. I am talking about supporting ANOTHER firmware. If someone bought the OpenEdition version, the only option for them is to flash it with 868 OpenRTX. But ESP32APRS_T-TWR does not support working with it.

Therefore, I suggest adding to ESP32APRS_T-TWR the ability to communicate with 868 via i2c, bypassing AT commands. In this way, there will be two options: NiceRF and OpenEdition with OpenRTX fw.

So, here https://github.com/nakhonthai/ESP32APRS_T-TWR/blob/main/src/main.cpp#L1448, add another option config.rf_type == RF_SA868_VHF_**open**

where instead of AT commands, the configuration will be done via i2c.

(Of course, it's desirable to use abstraction).

**Comment by lyusupov** [comment]
This PR https://github.com/nakhonthai/ESP32APRS_T-TWR/pull/17 reports a positive operation with https://github.com/OpenRTX/sa8x8-fw.

> Hardware does not support updates direct from ESP32,

T-TWR V2.0 does not...
However, upcoming V2.1 hardware revision provides circuits sufficient to program the SA868 module by ESP32-S3.
